<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fec23d91-f248-4512-9ec3-80f9278acbd4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsisyaApi.Application\AsisyaApi.Application.csproj" />
    <ProjectReference Include="..\AsisyaApi.Infrastructure\AsisyaApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
